import { model } from "@meridian/framework-utils"

const Notification = model.define("notification", {
  id: model.id().primaryKey(),
  /** The user who should receive this notification */
  user_id: model.text(),
  /** Domain entity type (issue, project, sprint, comment) */
  entity_type: model.text(),
  /** ID of the entity this notification is about */
  entity_id: model.text(),
  /** The action that triggered this notification (created, assigned, status_changed, commented) */
  action: model.text(),
  /** Human-readable message — optional, generated by the subscriber */
  message: model.text().nullable(),
  /** Whether the user has read this notification */
  read: model.boolean().default(false),
  workspace_id: model.text(),
})

export default Notification
